# Generated by Django 5.2.4 on 2025-07-04 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "grade_applied",
                    models.CharField(
                        choices=[
                            ("1 año", "1 año"),
                            ("2 años", "2 años"),
                            ("4 años", "4 años"),
                            ("5 años", "5 años"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dni", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("dni", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="AdmissionStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Entrevista", "Entrevista"),
                            ("Convivencia", "Convivencia"),
                            ("Matrícula", "Matrícula"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.applicant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="applicant",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="admission.parent",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("Banco de la Nación", "Banco de la Nación"),
                            ("BCP", "BCP"),
                        ],
                        max_length=30,
                    ),
                ),
                ("voucher_number", models.CharField(max_length=30)),
                ("payment_date", models.DateField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.applicant",
                    ),
                ),
            ],
        ),
    ]
