# Generated by Django 5.2.4 on 2025-07-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='has_siblings_in_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='siblings',
            field=models.ManyToManyField(blank=True, to='admission.applicant'),
        ),
    ]
