# Generated by Django 5.2.4 on 2025-07-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_applicant_has_siblings_in_school_applicant_siblings'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='parent',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Técnico', 'Técnico'), ('Universitario', 'Universitario'), ('Posgrado', 'Posgrado')], max_length=50, verbose_name='Nivel educativo'),
        ),
        migrations.AddField(
            model_name='parent',
            name='has_university_affiliation',
            field=models.BooleanField(default=False, verbose_name='¿Tiene vínculo con la universidad?'),
        ),
        migrations.AddField(
            model_name='parent',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Conviviente', 'Conviviente')], max_length=20, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='parent',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='dni',
            field=models.CharField(max_length=10, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
    ]
