# Generated by Django 5.2.4 on 2025-07-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_parent_address_parent_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='university_area',
            field=models.CharField(blank=True, max_length=100, verbose_name='Área o dependencia'),
        ),
        migrations.AddField(
            model_name='parent',
            name='university_relationship_details',
            field=models.TextField(blank=True, verbose_name='Detalles del vínculo'),
        ),
        migrations.AddField(
            model_name='parent',
            name='university_role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo en la universidad'),
        ),
    ]
