# Generated by Django 5.2.1 on 2025-07-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_parent_university_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='grade_applied',
            field=models.CharField(choices=[('1 año', '1 año'), ('2 años', '2 años'), ('3 años', '3 años'), ('4 años', '4 años'), ('5 años', '5 años')], max_length=10),
        ),
    ]
