# Generated by Django 5.2.1 on 2025-07-30 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_applicant_grade_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_admitted',
            field=models.BooleanField(default=False, verbose_name='Admitido'),
        ),
        migrations.CreateModel(
            name='AdmissionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrevista', models.BooleanField(default=False)),
                ('convivencia', models.BooleanField(default=False)),
                ('matricula', models.BooleanField(default=False)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_process', to='admission.applicant')),
            ],
        ),
        migrations.DeleteModel(
            name='AdmissionStage',
        ),
    ]
